### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZskY-Edward** [Oshekher-git/AdityaRDP#11]
Run Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
Invoke-WebRequest: D:\a\_temp\53f683ec-fc7d-4482-915b-21c6cafdf198.ps1:3
Line |
   3 |  Invoke-WebRequest https://raw.githubusercontent.com/Oshekher/AdityaRD …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 404: Not Found

Error: Process completed with exit code 1.

**Comment by Oshekher** [comment]
upstream the code you are using outdated version

**Comment by Oshekher-git** [comment]
Try this : https://github.com/Oshekher-git/Oshekher-RDP
